config/routes.rb
Rails.application.routes.draw do
  get 'home/index' 
  root 'home#index'
  resources :usuarios
  resources :contas_a_recebers
  resources :contas_a_pagars
  resources :tipo_de_conta
  resources :fornecedors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  before_action :set_fornecedor, only: [:show, :edit, :update, :destroy]

  # GET /fornecedors
  # GET /fornecedors.json
  def index
    @fornecedors = Fornecedor.all
  end

  # GET /fornecedors/1
  # GET /fornecedors/1.json
  def show
  end

  # GET /fornecedors/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedors/1/edit
  def edit
  end

  # POST /fornecedors
  # POST /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully created.' }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedors/1
  # PATCH/PUT /fornecedors/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1
  # DELETE /fornecedors/1.json
  def destroy
    @fornecedor.destroy
    respond_to do |format|
      format.html { redirect_to fornecedors_url, notice: 'Fornecedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nomeFantasia, :razaoSocial, :CNPJ, :inscricaoEstadual, :ramoAtividade, :CNAE)
    end
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/views/fornecedors/_form.html.erb
<%= form_with(model: fornecedor, local: true) do |form| %>
  <% if fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
      <% fornecedor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nomeFantasia %>
    <%= form.text_field :nomeFantasia, id: :fornecedor_nomeFantasia %>
  </div>

  <div class="field">
    <%= form.label :razaoSocial %>
    <%= form.text_field :razaoSocial, id: :fornecedor_razaoSocial %>
  </div>

  <div class="field">
    <%= form.label :CNPJ %>
    <%= form.text_field :CNPJ, id: :fornecedor_CNPJ %>
  </div>

  <div class="field">
    <%= form.label :inscricaoEstadual %>
    <%= form.text_field :inscricaoEstadual, id: :fornecedor_inscricaoEstadual %>
  </div>

  <div class="field">
    <%= form.label :ramoAtividade %>
    <%= form.text_field :ramoAtividade, id: :fornecedor_ramoAtividade %>
  </div>

  <div class="field">
    <%= form.label :CNAE %>
    <%= form.text_field :CNAE, id: :fornecedor_CNAE %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fornecedors/edit.html.erb
<h1>Editing Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Show', @fornecedor %> |
<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fornecedores</h1>

<table>
  <thead>
    <tr>
      <th>Nome Fantasia</th>
      <th>Razão Social</th>
      <th>Cnpj</th>
      <th>Inscrição Estadual</th>
      <th>Ramo Atividade</th>
      <th>Cnae</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fornecedors.each do |fornecedor| %>
      <tr>
        <td><%= fornecedor.nomeFantasia %></td>
        <td><%= fornecedor.razaoSocial %></td>
        <td><%= fornecedor.CNPJ %></td>
        <td><%= fornecedor.inscricaoEstadual %></td>
        <td><%= fornecedor.ramoAtividade %></td>
        <td><%= fornecedor.CNAE %></td>
        <td><%= link_to 'Show', fornecedor %></td>
        <td><%= link_to 'Edit', edit_fornecedor_path(fornecedor) %></td>
        <td><%= link_to 'Destroy', fornecedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fornecedor', new_fornecedor_path %>

app/views/fornecedors/new.html.erb
<h1>New Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome Fantasia:</strong>
  <%= @fornecedor.nomeFantasia %>
</p>

<p>
  <strong>Razão Social:</strong>
  <%= @fornecedor.razaoSocial %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @fornecedor.CNPJ %>
</p>

<p>
  <strong>Inscrição Estadual:</strong>
  <%= @fornecedor.inscricaoEstadual %>
</p>

<p>
  <strong>Ramo Atividade:</strong>
  <%= @fornecedor.ramoAtividade %>
</p>

<p>
  <strong>Cnae:</strong>
  <%= @fornecedor.CNAE %>
</p>

<%= link_to 'Edit', edit_fornecedor_path(@fornecedor) %> |
<%= link_to 'Back', fornecedors_path %>