config/routes.rb
Rails.application.routes.draw do
  get 'home/index' 
  root 'home#index'
  resources :usuarios
  resources :contas_a_recebers
  resources :contas_a_pagars
  resources :tipo_de_conta
  resources :fornecedors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contas_a_pagar.rb
class ContasAPagar < ApplicationRecord
end

app/controllers/contas_a_pagars_controller.rb
class ContasAPagarsController < ApplicationController
  before_action :set_contas_a_pagar, only: [:show, :edit, :update, :destroy]

  # GET /contas_a_pagars
  # GET /contas_a_pagars.json
  def index
    @contas_a_pagars = ContasAPagar.all
  end

  # GET /contas_a_pagars/1
  # GET /contas_a_pagars/1.json
  def show
  end

  # GET /contas_a_pagars/new
  def new
    @contas_a_pagar = ContasAPagar.new
  end

  # GET /contas_a_pagars/1/edit
  def edit
  end

  # POST /contas_a_pagars
  # POST /contas_a_pagars.json
  def create
    @contas_a_pagar = ContasAPagar.new(contas_a_pagar_params)

    respond_to do |format|
      if @contas_a_pagar.save
        format.html { redirect_to @contas_a_pagar, notice: 'Contas a pagar was successfully created.' }
        format.json { render :show, status: :created, location: @contas_a_pagar }
      else
        format.html { render :new }
        format.json { render json: @contas_a_pagar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contas_a_pagars/1
  # PATCH/PUT /contas_a_pagars/1.json
  def update
    respond_to do |format|
      if @contas_a_pagar.update(contas_a_pagar_params)
        format.html { redirect_to @contas_a_pagar, notice: 'Contas a pagar was successfully updated.' }
        format.json { render :show, status: :ok, location: @contas_a_pagar }
      else
        format.html { render :edit }
        format.json { render json: @contas_a_pagar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contas_a_pagars/1
  # DELETE /contas_a_pagars/1.json
  def destroy
    @contas_a_pagar.destroy
    respond_to do |format|
      format.html { redirect_to contas_a_pagars_url, notice: 'Contas a pagar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contas_a_pagar
      @contas_a_pagar = ContasAPagar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contas_a_pagar_params
      params.require(:contas_a_pagar).permit(:emissor, :dataEmissao, :valor, :descricaoConta, :valorMulta, :PermitePagarAposVencimento, :codigoBarras, :anexoConta)
    end
end

app/helpers/contas_a_pagars_helper.rb
module ContasAPagarsHelper
end

app/views/contas_a_pagars/_form.html.erb
<%= form_with(model: contas_a_pagar, local: true) do |form| %>
  <% if contas_a_pagar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contas_a_pagar.errors.count, "error") %> prohibited this contas_a_pagar from being saved:</h2>

      <ul>
      <% contas_a_pagar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :emissor %>
    <%= form.text_field :emissor, id: :contas_a_pagar_emissor %>
  </div>

  <div class="field">
    <%= form.label :dataEmissao %>
    <%= form.datetime_select :dataEmissao, id: :contas_a_pagar_dataEmissao %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor, id: :contas_a_pagar_valor %>
  </div>

  <div class="field">
    <%= form.label :descricaoConta %>
    <%= form.text_field :descricaoConta, id: :contas_a_pagar_descricaoConta %>
  </div>

  <div class="field">
    <%= form.label :valorMulta %>
    <%= form.text_field :valorMulta, id: :contas_a_pagar_valorMulta %>
  </div>

  <div class="field">
    <%= form.label :PermitePagarAposVencimento %>
    <%= form.check_box :PermitePagarAposVencimento, id: :contas_a_pagar_PermitePagarAposVencimento %>
  </div>

  <div class="field">
    <%= form.label :codigoBarras %>
    <%= form.text_field :codigoBarras, id: :contas_a_pagar_codigoBarras %>
  </div>

  <div class="field">
    <%= form.label :anexoConta %>
    <%= form.text_field :anexoConta, id: :contas_a_pagar_anexoConta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contas_a_pagars/edit.html.erb
<h1>Editing Contas A Pagar</h1>

<%= render 'form', contas_a_pagar: @contas_a_pagar %>

<%= link_to 'Show', @contas_a_pagar %> |
<%= link_to 'Back', contas_a_pagars_path %>

app/views/contas_a_pagars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contas A Pagar</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Emissor</th>
      <th>Data emissão</th>
      <th>Valor</th>
      <th>Descrição</th>
      <th>Multa por atraso</th>
      <th>Permite pagara pós vencimento</th>
      <th>Codigo barras</th>
      <th>Anexo da conta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contas_a_pagars.each do |contas_a_pagar| %>
      <tr>
        <td><%= contas_a_pagar.emissor %></td>
        <td><%= contas_a_pagar.dataEmissao %></td>
        <td><%= contas_a_pagar.valor %></td>
        <td><%= contas_a_pagar.descricaoConta %></td>
        <td><%= contas_a_pagar.valorMulta %></td>
        <td><%= contas_a_pagar.PermitePagarAposVencimento %></td>
        <td><%= contas_a_pagar.codigoBarras %></td>
        <td><%= contas_a_pagar.anexoConta %></td>
        <td><%= link_to 'Show', contas_a_pagar %></td>
        <td><%= link_to 'Edit', edit_contas_a_pagar_path(contas_a_pagar) %></td>
        <td><%= link_to 'Destroy', contas_a_pagar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contas A Pagar', new_contas_a_pagar_path %>

app/views/contas_a_pagars/new.html.erb
<h1>New Contas A Pagar</h1>

<%= render 'form', contas_a_pagar: @contas_a_pagar %>

<%= link_to 'Back', contas_a_pagars_path %>

app/views/contas_a_pagars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emissor:</strong>
  <%= @contas_a_pagar.emissor %>
</p>

<p>
  <strong>Dataemissao:</strong>
  <%= @contas_a_pagar.dataEmissao %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @contas_a_pagar.valor %>
</p>

<p>
  <strong>Descricaoconta:</strong>
  <%= @contas_a_pagar.descricaoConta %>
</p>

<p>
  <strong>Valormulta:</strong>
  <%= @contas_a_pagar.valorMulta %>
</p>

<p>
  <strong>Permitepagaraposvencimento:</strong>
  <%= @contas_a_pagar.PermitePagarAposVencimento %>
</p>

<p>
  <strong>Codigobarras:</strong>
  <%= @contas_a_pagar.codigoBarras %>
</p>

<p>
  <strong>Anexoconta:</strong>
  <%= @contas_a_pagar.anexoConta %>
</p>

<%= link_to 'Edit', edit_contas_a_pagar_path(@contas_a_pagar) %> |
<%= link_to 'Back', contas_a_pagars_path %>