config/routes.rb
Rails.application.routes.draw do
  get 'home/index' 
  root 'home#index'
  resources :usuarios
  resources :contas_a_recebers
  resources :contas_a_pagars
  resources :tipo_de_conta
  resources :fornecedors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contas_a_receber.rb
class ContasAReceber < ApplicationRecord
end

app/controllers/contas_a_recebers_controller.rb
class ContasARecebersController < ApplicationController
  before_action :set_contas_a_receber, only: [:show, :edit, :update, :destroy]

  # GET /contas_a_recebers
  # GET /contas_a_recebers.json
  def index
    @contas_a_recebers = ContasAReceber.all
  end

  # GET /contas_a_recebers/1
  # GET /contas_a_recebers/1.json
  def show
  end

  # GET /contas_a_recebers/new
  def new
    @contas_a_receber = ContasAReceber.new
  end

  # GET /contas_a_recebers/1/edit
  def edit
  end

  # POST /contas_a_recebers
  # POST /contas_a_recebers.json
  def create
    @contas_a_receber = ContasAReceber.new(contas_a_receber_params)

    respond_to do |format|
      if @contas_a_receber.save
        format.html { redirect_to @contas_a_receber, notice: 'Contas a receber was successfully created.' }
        format.json { render :show, status: :created, location: @contas_a_receber }
      else
        format.html { render :new }
        format.json { render json: @contas_a_receber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contas_a_recebers/1
  # PATCH/PUT /contas_a_recebers/1.json
  def update
    respond_to do |format|
      if @contas_a_receber.update(contas_a_receber_params)
        format.html { redirect_to @contas_a_receber, notice: 'Contas a receber was successfully updated.' }
        format.json { render :show, status: :ok, location: @contas_a_receber }
      else
        format.html { render :edit }
        format.json { render json: @contas_a_receber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contas_a_recebers/1
  # DELETE /contas_a_recebers/1.json
  def destroy
    @contas_a_receber.destroy
    respond_to do |format|
      format.html { redirect_to contas_a_recebers_url, notice: 'Contas a receber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contas_a_receber
      @contas_a_receber = ContasAReceber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contas_a_receber_params
      params.require(:contas_a_receber).permit(:emissor, :dataEmissao, :dataPagamento, :valor, :dataRecebimento, :valorMulta, :valorTotal)
    end
end

app/helpers/contas_a_recebers_helper.rb
module ContasARecebersHelper
end

app/views/contas_a_recebers/_form.html.erb
<%= form_with(model: contas_a_receber, local: true) do |form| %>
  <% if contas_a_receber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contas_a_receber.errors.count, "error") %> prohibited this contas_a_receber from being saved:</h2>

      <ul>
      <% contas_a_receber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :emissor %>
    <%= form.text_field :emissor, id: :contas_a_receber_emissor %>
  </div>

  <div class="field">
    <%= form.label :dataEmissao %>
    <%= form.datetime_select :dataEmissao, id: :contas_a_receber_dataEmissao %>
  </div>

  <div class="field">
    <%= form.label :dataPagamento %>
    <%= form.datetime_select :dataPagamento, id: :contas_a_receber_dataPagamento %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor, id: :contas_a_receber_valor %>
  </div>

  <div class="field">
    <%= form.label :dataRecebimento %>
    <%= form.datetime_select :dataRecebimento, id: :contas_a_receber_dataRecebimento %>
  </div>

  <div class="field">
    <%= form.label :valorMulta %>
    <%= form.text_field :valorMulta, id: :contas_a_receber_valorMulta %>
  </div>

  <div class="field">
    <%= form.label :valorTotal %>
    <%= form.text_field :valorTotal, id: :contas_a_receber_valorTotal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contas_a_recebers/edit.html.erb
<h1>Editing Contas A Receber</h1>

<%= render 'form', contas_a_receber: @contas_a_receber %>

<%= link_to 'Show', @contas_a_receber %> |
<%= link_to 'Back', contas_a_recebers_path %>

app/views/contas_a_recebers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contas A Recebers</h1>

<table>
  <thead>
    <tr>
      <th>Emissor</th>
      <th>Dataemissao</th>
      <th>Datapagamento</th>
      <th>Valor</th>
      <th>Datarecebimento</th>
      <th>Valormulta</th>
      <th>Valortotal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contas_a_recebers.each do |contas_a_receber| %>
      <tr>
        <td><%= contas_a_receber.emissor %></td>
        <td><%= contas_a_receber.dataEmissao %></td>
        <td><%= contas_a_receber.dataPagamento %></td>
        <td><%= contas_a_receber.valor %></td>
        <td><%= contas_a_receber.dataRecebimento %></td>
        <td><%= contas_a_receber.valorMulta %></td>
        <td><%= contas_a_receber.valorTotal %></td>
        <td><%= link_to 'Show', contas_a_receber %></td>
        <td><%= link_to 'Edit', edit_contas_a_receber_path(contas_a_receber) %></td>
        <td><%= link_to 'Destroy', contas_a_receber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contas A Receber', new_contas_a_receber_path %>

app/views/contas_a_recebers/new.html.erb
<h1>New Contas A Receber</h1>

<%= render 'form', contas_a_receber: @contas_a_receber %>

<%= link_to 'Back', contas_a_recebers_path %>

app/views/contas_a_recebers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emissor:</strong>
  <%= @contas_a_receber.emissor %>
</p>

<p>
  <strong>Dataemissao:</strong>
  <%= @contas_a_receber.dataEmissao %>
</p>

<p>
  <strong>Datapagamento:</strong>
  <%= @contas_a_receber.dataPagamento %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @contas_a_receber.valor %>
</p>

<p>
  <strong>Datarecebimento:</strong>
  <%= @contas_a_receber.dataRecebimento %>
</p>

<p>
  <strong>Valormulta:</strong>
  <%= @contas_a_receber.valorMulta %>
</p>

<p>
  <strong>Valortotal:</strong>
  <%= @contas_a_receber.valorTotal %>
</p>

<%= link_to 'Edit', edit_contas_a_receber_path(@contas_a_receber) %> |
<%= link_to 'Back', contas_a_recebers_path %>